### ISSUE TITLE
Add ruyisdk/llvm-project to ruyi package manager

### ISSUE THREAD

**Issue by imkiva** [ruyisdk/ruyi#137] opened 2024-05-07 06:20 UTC
[ruyisdk/llvm-project](https://github.com/ruyisdk/llvm-project) is a fork of LLVM 17.0.6, which supports [the T-Head Vector extension](https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadvector.adoc) by providing compiler builtin functions (intrinsics) on top of the upstream version.

To build this fork, use the following commands:

```bash
cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="clang" \
    -DLLVM_TARGETS_TO_BUILD="RISCV" \
    -DLLVM_DEFAULT_TARGET_TRIPLE="riscv64-unknown-linux-gnu"
```

Any questions or suggestions are welcomed, and we will try our best to help integrate this LLVM into the Ruyi Package Manager.

**Comment by xen0n** [comment] 2024-05-12 18:34
dupe of #121

**Closed by xen0n** 2024-05-12 18:34 UTC
Labels: duplicate
